menu:
 Archive: /archives
 Tags: /tags
 RSS: /atom.xml
 tag: /tags  #标签''页面的路径

widgets:
 - greeting
 - site_links

rss: /atom.xml

readMore: ...read more

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
